// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ARION.Models;

#nullable disable

namespace ARION.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240817125129_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ARION.Models.Anchor", b =>
                {
                    b.Property<int>("AnchorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnchorId"));

                    b.Property<string>("AnchorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalTime")
                        .HasColumnType("int");

                    b.Property<int>("TrackedPageId")
                        .HasColumnType("int");

                    b.HasKey("AnchorId");

                    b.HasIndex("TrackedPageId");

                    b.ToTable("Anchors");
                });

            modelBuilder.Entity("ARION.Models.TrackedPage", b =>
                {
                    b.Property<int>("TrackedPageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackedPageId"));

                    b.Property<bool>("IsDataCollectionActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHeatmapShown")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalPageViews")
                        .HasColumnType("int");

                    b.Property<int?>("TotalViewTime")
                        .HasColumnType("int");

                    b.HasKey("TrackedPageId");

                    b.ToTable("TrackedPages");
                });

            modelBuilder.Entity("ARION.Models.Anchor", b =>
                {
                    b.HasOne("ARION.Models.TrackedPage", "TrackedPage")
                        .WithMany("Anchors")
                        .HasForeignKey("TrackedPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedPage");
                });

            modelBuilder.Entity("ARION.Models.TrackedPage", b =>
                {
                    b.Navigation("Anchors");
                });
#pragma warning restore 612, 618
        }
    }
}
